blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('edit<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='previews/', verbose_name='изображение')
    date = models.DateField(auto_now_add=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title} - {self.body[:100]} ({self.date})'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        permissions = [
            ('change_blog_status', 'Can change blog theme status')
        ]

blog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Блог',
    }

    def get_queryset(self):
        user = self.request.user
        if not user.has_perm('blog.change_blog') and not user.has_perm('blog.change_blog_status'):
            return Blog.objects.filter(is_published=True)
        return Blog.objects.all()


class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'body')
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def has_permission(self):
        user = self.request.user
        return user.groups.filter(name='content manager').exists()


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'body')
    template_name = 'blog/blog_form.html'
    permission_required = 'blog.change_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_blog'


@permission_required('blog.change_blog_status')
def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить статью "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="row">
    <div class="col-12">
        <hr>
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            <span class="text-muted">{{ object.title }}</span>
        </h3>
        <p>{{ object.body }}</p>
        <div class="col">
            <div class="card-footer">
                Просмотры {{ object.views_count }}
            </div>
            <p class="blog-post-meta">Опубликовано: {{ object.date }}
        </div>
        <a href="{% url 'blog:list' %}" type="button"
           class="btn btn-sm btn-outline-secondary">Назад</a>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_menu.html' %}

<div class="col-12 mb-5">
    {% if perms.blog.add_blog %}
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать тему</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="row">
    <div class="col-12">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            {% if object.is_published %}
            {{ object.title}}
            {% else %}
            <span class="text-muted">{{ object.title }}</span>
            {% endif %}
        </h3>
        <p>{{ object.body }}</p>
        <div class="col">
            <p class="blog-post-meta">Опубликовано: {{ object.date }}
            <div class="card-footer">slug: {{ object.slug }} Просмотры {{ object.views_count }}</div>
            <p></p>
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:view' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Читать</a>
                            {% if perms.blog.change_blog %}
                            <a href="{% url 'blog:edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Правка</a>
                            {% endif %}
                            {% if perms.blog.delete_blog %}
                            <a href="{% url 'blog:delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% endif %}
                        </div>
                        {% if perms.blog.change_blog_status %}
                        {% if object.is_published %}
                        <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}">Снять с
                            публикации</a>
                        {% else %}
                        <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk %}">Опубликовать</a>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}