blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('edit<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify, ResetPasswordView, \
    NewPassGenerateView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>', verify, name='verify'),
    path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
    path('new_pass_generate/', NewPassGenerateView.as_view(), name='new_pass_generate')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.jpg', verbose_name='аватар')
    telegram = models.CharField(max_length=150, verbose_name='телеграм', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=40, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=50, verbose_name='токен')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms

from catalog.forms import MixinFormControl
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm

from users.models import User


class UserRegisterForm(MixinFormControl, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(MixinFormControl, UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'telegram', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class ResetPasswordForm(MixinFormControl, PasswordResetForm):
    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
        except Exception:
            raise forms.ValidationError('Пользователь с такой почтой не зарегистрирован')

        return email

    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email,
                  html_email_template_name=None):
        pass

users/views.py
import secrets
import string

from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm, ResetPasswordForm
from users.models import User
from config import settings


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def get_success_url(self):
        return reverse('users:login')

    def form_valid(self, form):
        user = form.save()
        token = secrets.token_hex(16)
        user.token = token
        user.is_active = False
        user.save()
        host = self.request.get_host()  # 127.0.0.1:8000
        url = f'http://{host}/users/verify/{token}'
        message = f'Для подтверждения верификации почты необходимо перейти по ссылке: {url}'
        send_mail('Верификация почты', message, settings.EMAIL_HOST_USER, [user.email])
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def verify(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ResetPasswordView(PasswordResetView):

    form_class = ResetPasswordForm
    template_name = 'users/reset_password.html'
    email_template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('users:new_pass_generate')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        user = User.objects.get(email=email)

        alphabet = string.ascii_letters + string.digits
        password = "".join(secrets.choice(alphabet) for i in range(10))
        user.password = make_password(password)
        user.save()
        message = f"Ваш новый пароль:\n{password}"
        send_mail(
            "Смена пароля",
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


class NewPassGenerateView(TemplateView):
    template_name = 'users/new_pass_generate.html'

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-5">

    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Вход
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
                <a href="{% url 'users:reset_password' %}" class="btn btn-primary">Восстановить пароль</a>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/new_pass_generate.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<div class="row">
    <div class="col-12">
        Новый пароль сгенерирован и отправлен на вашу почту.
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            Регистрация
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Восстановление пароля
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            Восстановить пароль
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

<div class="row">
    <div class="col-12">

        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Редактирование профиля
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                                Сохранить
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Аватар
                            </h3>
                        </div>
                        <div class="card-body">
                            <img class="card-img-top scaled-image" src="{{ user.avatar.url }}" alt="{{ user.avatar }}">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}