blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('edit<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import MainConfig
from catalog.views import ProductListView, ProductDetailView, ContactsTemplateView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, MyProductsListView, CategoryListView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('my_products/', MyProductsListView.as_view(), name='my_products'),
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify, ResetPasswordView, \
    NewPassGenerateView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>', verify, name='verify'),
    path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
    path('new_pass_generate/', NewPassGenerateView.as_view(), name='new_pass_generate')
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='категория')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('category_name',)


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='цена', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='опубликовать')

    objects = models.Manager()

    def __str__(self):
        return f'{self.product_name}, Категория: {self.category}, Цена: {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('product_name',)
        permissions = [
            ('change_description', 'Can change product description'),
            ('change_category', 'Can change product category'),
            ('change_published_status', 'Can change published status')
        ]


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version = models.IntegerField(verbose_name='версия')
    version_name = models.CharField(max_length=150, verbose_name='название версии')
    is_current_version = models.BooleanField(default=False, **NULLABLE, verbose_name='текущая версия')

    def __str__(self):
        return f'{self.product}: {self.version}, {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import ModelForm

from catalog.models import Product, Version


class MixinFormControl:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(MixinFormControl, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('owner',)

    def clean_product_name(self):
        product_name = self.cleaned_data['product_name']

        if product_name in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']:
            raise forms.ValidationError('Слово запрещено в названии продукта')
        return product_name


class VersionForm(MixinFormControl, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_version_name(self):
        valid_version = self.cleaned_data['version']

        if valid_version < 0:
            raise forms.ValidationError('Номер версии не может быть отрицательным')
        return valid_version


class ProductModeratorForm(MixinFormControl, ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse

from datetime import datetime

from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_products_from_cache, get_categories_from_cache


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        product = self.get_object()
        context['title'] = product.product_name

        active_version = Version.objects.filter(product=product, is_current_version=True).order_by('-id').first()
        if active_version is None:
            context['active_version'] = 'Отсутствует'
        else:
            context['active_version'] = active_version.version

        return context


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'object_list'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args,**kwargs)
        context_data['products_list'] = get_products_from_cache()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        version_form = context_data['formset']
        self.object = form.save()
        if version_form.is_valid():
            version_form.instance = self.object
            version_form.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if self.object.owner == user or user.is_superuser:
            return ProductForm
        elif user.has_perm('catalog.change_description') and user.has_perm('catalog.change_category'):
            return ProductModeratorForm
        raise Http404


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product

    def get_success_url(self):
        return reverse('catalog:index')


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        with open('log.txt', 'a', encoding='utf-8') as f:
            f.write(f'{datetime.now()} {name} ({phone}): {message}\n')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context


class MyProductsListView(ListView):
    model = Product
    template_name = 'catalog/my_product_list.html'
    context_object_name = 'object_list'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Мои продукты'
        products = context['object_list']

        for product in products:
            current_version = product.version_set.filter(is_current_version=True).order_by('-id').first()
            product.current_version = current_version

            if current_version is None:
                continue
            else:
                product.version = current_version.version
                product.version_name = product.current_version.version_name

        return context

    def get_queryset(self):

        user = self.request.user
        queryset = Product.objects.filter(owner=user)
        return queryset


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['categories_list'] = get_categories_from_cache()
        return context_data

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <div class="col-9">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
    </nav>
    </div>
    <div class="col-10">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-success" href="{% url 'users:logout' %}">Выход</a>
        <a class="btn btn-outline-success" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
        <a class="btn btn-outline-success" href="{% url 'users:login' %}">Войти</a>
        <a class="btn btn-outline-success" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row">

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
<title>Список категорий</title>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категории</h1>
</div>
<div class="col-12 mb-5">
    {% if request.user.is_authenticated %}
  <a href="{% url 'catalog:create' %}" class="btn btn-outline-primary">Добавить продукт</a>
    {% endif %}
</div>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
        {% for category in categories_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text"><strong>Категория: {{category.category_name}}</strong></p>
                  <p class="card-text">{{ category.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}

{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for object in object_list %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{object.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{object.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{object.price}} руб.</li>
                                <li>- Категория: {{ object.category.category_name }}</li>


                            </ul>
                            <a href="{% url 'catalog:product' object.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

<div class="container">
    <p>Недавно добавленные</p>
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for product in latest_products %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{product.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{product.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{product.price}}</li>
                                <li>- Категория: {{ product.category.category_name }}</li>
                            </ul>
                            <a href="{% url 'catalog:product' product.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/index_list.html
{% extends 'catalog/base.html' %}
{% block content %}

{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for object in object_list %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{object.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{object.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{object.price}} руб.</li>
                                <li>- Категория: {{ object.category.category_name }}</li>


                            </ul>
                            <a href="{% url 'catalog:product' object.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

<div class="container">
    <p>Недавно добавленные</p>
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for product in latest_products %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{product.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{product.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{product.price}}</li>
                                <li>- Категория: {{ product.category.category_name }}</li>
                            </ul>
                            <a href="{% url 'catalog:product' product.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/my_product_list.html
{% extends 'catalog/base.html' %}
{% block content %}

{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="row">
    <div class="col">
        {% if request.user.is_authenticated %}
        <a href="{% url 'catalog:create' %}" class="btn btn-primary">Добавить продукт</a>
        <a href="{% url 'catalog:my_products' %}" class="btn btn-primary">Мои продукты</a>
        {% endif %}
        <hr>
    </div>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for object in object_list %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{object.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{object.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{object.price}} руб.</li>
                                <li>- Категория: {{ object.category.category_name }}</li>
                                {% if object.current_version.version is None %}
                                <li>- Версия: Отсутствует</li>
                                {% else %}
                                <li>- Версия: {{ object.current_version.version }}, {{ object.version_name }}</li>
                                {% endif %}


                            </ul>
                            <a href="{% url 'catalog:product' object.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">подробнее>></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить товар "{{ object.product_name }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media_tags %}
{% block content %}
{% include 'catalog/includes/inc_menu.html' with objects=objects %}
<div class="container">
    <div class="row">
        <div class="col-md-5 mb-4">
            <div class="card box-shadow h-100">
                <img class="card-img-top" src="{{ product.image|mymedia }}" alt="{{ product.product_name }}">
                <div class="card-body">
                </div>
            </div>
            <a href="{% url 'catalog:index' %}" class="btn btn-lg btn-outline-primary" style="margin-top: 2px;">К
                каталогу</a>
            {% if request.user.is_authenticated and request.user == product.owner or perms.catalog.change_product %}
            <a href="{% url 'catalog:edit' object.pk %}" class="btn btn-lg btn-outline-primary"
               style="margin-top: 2px;">Редактировать</a>
            {% endif %}
            {% if request.user == product.owner or user.is_superuser %}
            <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-lg btn-outline-primary"
               style="margin-top: 2px;">Удалить</a>
            {% endif %}
            <p>Активная версия: {{ active_version }}</p>
        </div>

        <div class="col-md-6">
            <div class="card box-shadow h-100">
                <div class="card-body">
                    <p class="card-text fs-4">Описание: {{ product.description }}</p>
                    <p class="card-text fw-bold fs-2">Цена: {{ product.price }} руб.</p>
                </div>
                <div style="margin-top: 2px;" class="d-grid">
                    <button type="button" class="form-control btn btn-lg btn-block btn-outline-primary">Купить</button>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load static %}


{% block content %}

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-header" style="margin-bottom: 7px;">
                        {% if product %}
                        <h4 class="card-title">Редактировать продукт</h4>
                        {% else %}
                        <h4 class="card-title">Добавить продукт</h4>
                        {% endif %}
                    </div>
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if product %}
                    <br>
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                    <br>
                    <button type="submit" class="btn btn-success">Создать</button>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-6">
            {% if product %}
            {% if perms.catalog.change_version or product.owner == request.user %}
            <div class="card">
                <div class="card-body">
                <div class="card-header" style="margin-bottom: 7px;">
                    <h4 class="card-title">Версии продукта</h4>
                </div>

                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}

</form>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}

{% include 'catalog/includes/inc_menu.html' with objects=objects %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="row">
    <div class="col">
        {% if request.user.is_authenticated %}
        <a href="{% url 'catalog:create' %}" class="btn btn-primary">Добавить продукт</a>
        <a href="{% url 'catalog:my_products' %}" class="btn btn-primary">Мои продукты</a>
        {% endif %}
        <hr>
    </div>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for object in object_list %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{object.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{object.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{object.price}} руб.</li>
                                <li>- Категория: {{ object.category.category_name }}</li>
                                {% if object.current_version.version is None %}
                                <li>- Версия: Отсутствует</li>
                                {% else %}
                                <li>- Версия: {{ object.current_version.version }}, {{ object.version_name }}
                                </li>
                                {% endif %}


                            </ul>
                            <a href="{% url 'catalog:product' object.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">подробнее>></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

<div class="container">
    <p>Недавно добавленные</p>
    <div class="row text-center">
        <div class="col-3-md3">

            <div class="row">
                {% for product in latest_products %}
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{product.product_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- Описание: {{product.description|truncatechars:'100' }}</li>
                                <li>- Цена: {{product.price}}</li>
                                <li>- Категория: {{ product.category.category_name }}</li>

                            </ul>
                            <a href="{% url 'catalog:product' product.pk %}" type="button"
                               class="form-control btn btn-lg btn-block btn-outline-primary">Купить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}